name: GitHub Readme YouTube Cards
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        id: youtube-cards
        with:
          channel_id: UCipSxT7a3rn81vGLw9lqRkg
          output_only: "true"
      - run: echo OUTPUT '${{ steps.youtube-cards.outputs.markdown }}'
        shell: bash
steps:
  - uses: DenverCoder1/github-readme-youtube-cards@main
    with:
      channel_id: UCipSxT7a3rn81vGLw9lqRkg
      comment_tag_name: YOUTUBE-CARDS
      youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
      show_duration: true
