name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  push:
    # run when the workflow file is modified
    branches:
      - main
    paths:
      - ".github/workflows/youtube-cards.yml"
  # run when dispatched from actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses:  Dakalo-Ndonde15/Dakalo-Ndonde15@main
        with:
          channel_id: UCers8q51YG5Q1ModcahhIEw
          comment_tag_name: YOUTUBE-CARDS
          max_title_lines: 2
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true
          output_type: html
